import disnake

# fmt: off

_all = _all = disnake.Embed.from_dict({"fields": [{"inline": False,"name": "Arugments","value": "Requirements or options applying to all commands except special cases",},{"inline": False,"name": "Data:","value": "Data is a a string passed as an arugment",},{"inline": False,"name": "Files","value": "File is uploaded to discords cdn and code redirects to a link",},{"inline": False,"name": "Error Correction","value": " an optional percentage value of the codes error correction",},{"inline": False,"name": "Resources:","value": "Websites Providing info",},{"inline": True,"name": "Beaconstac","value": "https://www.beaconstac.com/what-is-qr-code",},{"inline": True,"name": "Wikipedia","value": "https://en.wikipedia.org/wiki/QR_code",},],"color": disnake.Color.random(),"type": "rich","description": "Mode: All","title": "QR Code help",})
_auto = disnake.Embed.from_dict({"fields": [{"inline": False,"name": "Fucntion:","value": "Auto generates a simple code from the given data without much configuration",},{"inline": True, "name": "Required:", "value": "Data or a file"},],"color": disnake.Color.random(),"type": "rich","description": "Mode: Auto","title": "QR Code help",})
_stylized = disnake.Embed.from_dict({"fields": [{"inline": False,"name": "Function:","value": "Generates a stylized code from the given data using the provided configuration",},{"inline": True, "name": "Required:", "value": "Data or a file"},{"inline": True,"name": "Options:","value": "bg and fg colors formatted in comma sepertaed RGB values",},{"inline": True, "name": "Optional:", "value": "error correction margin"},],"color": disnake.Color.random(),"type": "rich","description": "Mode: Stylized","title": "QR Code help",})
_ascii = disnake.Embed.from_dict({"fields": [{"inline": False,"name": "Function:","value": "Generates an ascii code from the given data",},{"inline": True, "name": "Required:", "value": "Data or a file"},{"inline": True,"name": "as_file:","value": "Uploads as a file instead of a codeblock",},{"inline": True, "name": "Optional:", "value": "error correction margin"},],"color": disnake.Color.random(),"type": "rich","description": "Mode: Ascii","title": "QR Code help",})
_svg = disnake.Embed.from_dict({"fields": [{"inline": False,"name": "Function:","value": "Generates a SVG code from the given data",},{"inline": True,"name": "Required:","value": "Data or a file",},{"inline": True, "name": "Optional:", "value": "error correction margin"},],"color": disnake.Color.random(),"type": "rich","description": "Mode: SVG","title": "QR Code help",})

# a key to emebed maping for the help message
full = {"All":_all,"Auto":_auto,"Stylized":_stylized,"Ascii":_ascii,"SVG":_svg}
